#!/usr/bin/env bash

# Update packages
sudo apt-get update
sudo apt-get install -y nginx

# Create index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform a 301 redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/KwameNtaadu007 permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Create an HTTP response header
sudo sed -i "/server_name _/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Test configurations for syntax errors
sudo nginx -t

# Restart nginx to apply changes
sudo service nginx restart
