#!/usr/bin/env bash
# As a build up on task 0. -f flag is added to ln to forcefully remove the file if it exists
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
rm /run/nginx.pid
