#!/usr/bin/env bash
# Script which displays 12 hours: 0-12 and 59 minutes: 1-59

hour=0

while [ "$hour" -le 12 ]
do
	echo "Hour: $hour"
	(( hour++ ))

	minute=1
	while [ "$minute" -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
done

